
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Table tableBox;
	
	private global::Gtk.Button button1;
	
	private global::Gtk.Button button2;
	
	private global::Gtk.Button button3;
	
	private global::Gtk.Button button4;
	
	private global::Gtk.Button button5;
	
	private global::Gtk.Button button6;
	
	private global::Gtk.Button button7;
	
	private global::Gtk.Button button8;
	
	private global::Gtk.Button button9;
	
	private global::Gtk.Button buttonAdd;
	
	private global::Gtk.Button buttonC;
	
	private global::Gtk.Button buttonDivide;
	
	private global::Gtk.Button buttonEqual;
	
	private global::Gtk.Button buttonMultiply;
	
	private global::Gtk.Button buttonSubtract;
	
	private global::Gtk.Button buttonZero;
	
	private global::Gtk.Entry input;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Calculator for 1st form kids");
		this.WindowPosition = ((global::Gtk.WindowPosition)(2));
		this.DefaultWidth = 280;
		this.DefaultHeight = 330;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.tableBox = new global::Gtk.Table (((uint)(5)), ((uint)(4)), false);
		this.tableBox.WidthRequest = 0;
		this.tableBox.HeightRequest = 0;
		this.tableBox.Name = "tableBox";
		// Container child tableBox.Gtk.Table+TableChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("1");
		this.tableBox.Add (this.button1);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.tableBox [this.button1]));
		w1.TopAttach = ((uint)(3));
		w1.BottomAttach = ((uint)(4));
		w1.XOptions = ((global::Gtk.AttachOptions)(4));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableBox.Gtk.Table+TableChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString ("2");
		this.tableBox.Add (this.button2);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.tableBox [this.button2]));
		w2.TopAttach = ((uint)(3));
		w2.BottomAttach = ((uint)(4));
		w2.LeftAttach = ((uint)(1));
		w2.RightAttach = ((uint)(2));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableBox.Gtk.Table+TableChild
		this.button3 = new global::Gtk.Button ();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString ("3");
		this.tableBox.Add (this.button3);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.tableBox [this.button3]));
		w3.TopAttach = ((uint)(3));
		w3.BottomAttach = ((uint)(4));
		w3.LeftAttach = ((uint)(2));
		w3.RightAttach = ((uint)(3));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableBox.Gtk.Table+TableChild
		this.button4 = new global::Gtk.Button ();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString ("4");
		this.tableBox.Add (this.button4);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.tableBox [this.button4]));
		w4.TopAttach = ((uint)(2));
		w4.BottomAttach = ((uint)(3));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableBox.Gtk.Table+TableChild
		this.button5 = new global::Gtk.Button ();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString ("5");
		this.tableBox.Add (this.button5);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.tableBox [this.button5]));
		w5.TopAttach = ((uint)(2));
		w5.BottomAttach = ((uint)(3));
		w5.LeftAttach = ((uint)(1));
		w5.RightAttach = ((uint)(2));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableBox.Gtk.Table+TableChild
		this.button6 = new global::Gtk.Button ();
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString ("6");
		this.tableBox.Add (this.button6);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.tableBox [this.button6]));
		w6.TopAttach = ((uint)(2));
		w6.BottomAttach = ((uint)(3));
		w6.LeftAttach = ((uint)(2));
		w6.RightAttach = ((uint)(3));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableBox.Gtk.Table+TableChild
		this.button7 = new global::Gtk.Button ();
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.Label = global::Mono.Unix.Catalog.GetString ("7");
		this.tableBox.Add (this.button7);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.tableBox [this.button7]));
		w7.TopAttach = ((uint)(1));
		w7.BottomAttach = ((uint)(2));
		// Container child tableBox.Gtk.Table+TableChild
		this.button8 = new global::Gtk.Button ();
		this.button8.CanFocus = true;
		this.button8.Name = "button8";
		this.button8.UseUnderline = true;
		this.button8.Label = global::Mono.Unix.Catalog.GetString ("8");
		this.tableBox.Add (this.button8);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.tableBox [this.button8]));
		w8.TopAttach = ((uint)(1));
		w8.BottomAttach = ((uint)(2));
		w8.LeftAttach = ((uint)(1));
		w8.RightAttach = ((uint)(2));
		// Container child tableBox.Gtk.Table+TableChild
		this.button9 = new global::Gtk.Button ();
		this.button9.CanFocus = true;
		this.button9.Name = "button9";
		this.button9.UseUnderline = true;
		this.button9.Label = global::Mono.Unix.Catalog.GetString ("9");
		this.tableBox.Add (this.button9);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.tableBox [this.button9]));
		w9.TopAttach = ((uint)(1));
		w9.BottomAttach = ((uint)(2));
		w9.LeftAttach = ((uint)(2));
		w9.RightAttach = ((uint)(3));
		// Container child tableBox.Gtk.Table+TableChild
		this.buttonAdd = new global::Gtk.Button ();
		this.buttonAdd.CanFocus = true;
		this.buttonAdd.Name = "buttonAdd";
		this.buttonAdd.UseUnderline = true;
		this.buttonAdd.Label = global::Mono.Unix.Catalog.GetString ("+");
		this.tableBox.Add (this.buttonAdd);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.tableBox [this.buttonAdd]));
		w10.TopAttach = ((uint)(4));
		w10.BottomAttach = ((uint)(5));
		w10.LeftAttach = ((uint)(3));
		w10.RightAttach = ((uint)(4));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableBox.Gtk.Table+TableChild
		this.buttonC = new global::Gtk.Button ();
		this.buttonC.Name = "buttonC";
		this.buttonC.UseUnderline = true;
		this.buttonC.Label = global::Mono.Unix.Catalog.GetString ("C");
		this.tableBox.Add (this.buttonC);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.tableBox [this.buttonC]));
		w11.LeftAttach = ((uint)(3));
		w11.RightAttach = ((uint)(4));
		// Container child tableBox.Gtk.Table+TableChild
		this.buttonDivide = new global::Gtk.Button ();
		this.buttonDivide.CanFocus = true;
		this.buttonDivide.Name = "buttonDivide";
		this.buttonDivide.UseUnderline = true;
		this.buttonDivide.Label = global::Mono.Unix.Catalog.GetString ("/");
		this.tableBox.Add (this.buttonDivide);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.tableBox [this.buttonDivide]));
		w12.TopAttach = ((uint)(1));
		w12.BottomAttach = ((uint)(2));
		w12.LeftAttach = ((uint)(3));
		w12.RightAttach = ((uint)(4));
		// Container child tableBox.Gtk.Table+TableChild
		this.buttonEqual = new global::Gtk.Button ();
		this.buttonEqual.CanFocus = true;
		this.buttonEqual.Name = "buttonEqual";
		this.buttonEqual.UseUnderline = true;
		this.buttonEqual.Label = global::Mono.Unix.Catalog.GetString ("=");
		this.tableBox.Add (this.buttonEqual);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.tableBox [this.buttonEqual]));
		w13.TopAttach = ((uint)(4));
		w13.BottomAttach = ((uint)(5));
		w13.LeftAttach = ((uint)(2));
		w13.RightAttach = ((uint)(3));
		// Container child tableBox.Gtk.Table+TableChild
		this.buttonMultiply = new global::Gtk.Button ();
		this.buttonMultiply.CanFocus = true;
		this.buttonMultiply.Name = "buttonMultiply";
		this.buttonMultiply.UseUnderline = true;
		this.buttonMultiply.Label = global::Mono.Unix.Catalog.GetString ("*");
		this.tableBox.Add (this.buttonMultiply);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.tableBox [this.buttonMultiply]));
		w14.TopAttach = ((uint)(2));
		w14.BottomAttach = ((uint)(3));
		w14.LeftAttach = ((uint)(3));
		w14.RightAttach = ((uint)(4));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableBox.Gtk.Table+TableChild
		this.buttonSubtract = new global::Gtk.Button ();
		this.buttonSubtract.CanFocus = true;
		this.buttonSubtract.Name = "buttonSubtract";
		this.buttonSubtract.UseUnderline = true;
		this.buttonSubtract.Label = global::Mono.Unix.Catalog.GetString ("-");
		this.tableBox.Add (this.buttonSubtract);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.tableBox [this.buttonSubtract]));
		w15.TopAttach = ((uint)(3));
		w15.BottomAttach = ((uint)(4));
		w15.LeftAttach = ((uint)(3));
		w15.RightAttach = ((uint)(4));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableBox.Gtk.Table+TableChild
		this.buttonZero = new global::Gtk.Button ();
		this.buttonZero.CanFocus = true;
		this.buttonZero.Name = "buttonZero";
		this.buttonZero.UseUnderline = true;
		this.buttonZero.Label = global::Mono.Unix.Catalog.GetString ("0");
		this.tableBox.Add (this.buttonZero);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.tableBox [this.buttonZero]));
		w16.TopAttach = ((uint)(4));
		w16.BottomAttach = ((uint)(5));
		w16.RightAttach = ((uint)(2));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableBox.Gtk.Table+TableChild
		this.input = new global::Gtk.Entry ();
		this.input.CanFocus = true;
		this.input.Name = "input";
		this.input.IsEditable = true;
		this.input.WidthChars = 0;
		this.input.InvisibleChar = '•';
		this.tableBox.Add (this.input);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.tableBox [this.input]));
		w17.RightAttach = ((uint)(3));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		this.Add (this.tableBox);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.buttonZero.Clicked += new global::System.EventHandler (this.OnButtonNumberClick);
		this.buttonSubtract.Clicked += new global::System.EventHandler (this.OnButtonOperationClick);
		this.buttonMultiply.Clicked += new global::System.EventHandler (this.OnButtonOperationClick);
		this.buttonEqual.Clicked += new global::System.EventHandler (this.OnButtonOperationClick);
		this.buttonDivide.Clicked += new global::System.EventHandler (this.OnButtonOperationClick);
		this.buttonC.Clicked += new global::System.EventHandler (this.OnButtonClearClick);
		this.buttonAdd.Clicked += new global::System.EventHandler (this.OnButtonOperationClick);
		this.button9.Clicked += new global::System.EventHandler (this.OnButtonNumberClick);
		this.button8.Clicked += new global::System.EventHandler (this.OnButtonNumberClick);
		this.button7.Clicked += new global::System.EventHandler (this.OnButtonNumberClick);
		this.button6.Clicked += new global::System.EventHandler (this.OnButtonNumberClick);
		this.button5.Clicked += new global::System.EventHandler (this.OnButtonNumberClick);
		this.button4.Clicked += new global::System.EventHandler (this.OnButtonNumberClick);
		this.button3.Clicked += new global::System.EventHandler (this.OnButtonNumberClick);
		this.button2.Clicked += new global::System.EventHandler (this.OnButtonNumberClick);
		this.button1.Clicked += new global::System.EventHandler (this.OnButtonNumberClick);
	}
}
